### ISSUE TITLE
BCrypt Regression

### ISSUE THREAD

**Issue by Andrewangeta** [vapor/crypto#50]
<img width="971" alt="screen shot 2018-04-07 at 5 21 12 pm" src="https://user-images.githubusercontent.com/12012815/38469728-73c2ef6a-3b27-11e8-9d03-fd5f18680c7f.png">
Using the BCrypt static methods. (possibly the Digest also) takes over 20+ seconds to complete in routes.

``` swift
  let data = try BCrypt.make(message: "something")
            
  let seasonedPassword = String(bytes: data, encoding: .utf8)!
```
Using Crypto 3.0
macOS 10.13.3
Xcode 9.3

**Comment by damirstuhec** [comment]
Me too.

**Comment by mcdappdev** [comment]
I’m also worried about this api. It feels like it’s the only static method in my whole system and at this point feels wrong to not register as a service. I know it’s not the only static method but it sticks out wildly.

**Comment by tanner0101** [comment]
This is probably because the development cost used to be `4` and now it's `12` by default (which _should_ take a long time). That wouldn't be a regression (unless you can show BCrypt with cost 12 used to be faster). BCrypt being slow is a good thing.

> I’m also worried about this api, given that it's not registered as a service and is instead used statically.

@mcdappdev I believe hashing is a special case here. _Tons_ of things need hashing and usually they want to configure settings on their own (things like bcrypt cost). Registering hash algorithms through services is kind of overkill.

That said, if you want to dynamically change the cost based on environment, you can easily create your own wrapper that uses `BCrypt` statically or uses an instance of `BCryptDigest`. 

It might be easier to just switch on the environment where you actually use BCrypt as well.

```swift
router.post(CreateUser.self, "users") { req, createUser in
    let cost: Int
    if req.environment.isRelease {
        cost = 12
    } else {
        cost = 4
    }
    
    let hash = try BCrypt.hash(createUser.password, cost: cost)
    ... 
}
```

**Comment by mcdappdev** [comment]
Makes sense 👍 Thanks!

**Comment by 0xTim** [comment]
Even in production, taking 25s to hash a password isn't a good default...

**Comment by mcdappdev** [comment]
I wonder if performance is different in release mode?

**Comment by mcdappdev** [comment]
Ah, I can confirm that in production this is significantly better. 

```swift
    func bcrypt(req: Request) throws -> String {
        try BCrypt.hash("cost12", cost: 12)
        return "done"
    }
    
    router.get("/bcrypt", use: bcrypt)
```

In development, that route takes 25 seconds. In release, that route takes 381ms.

**Comment by 0xTim** [comment]
Ah interesting - @tanner0101 is this difference expected or should they be roughly similar?

**Comment by tanner0101** [comment]
@0xTim that's expected since the BCrypt implementation is written in Swift. It would be nice if we could wrap something from a C library so that there wouldn't be a difference in runtime between build modes.

**Comment by bre7** [comment]
@tanner0101 managed to get something working: https://github.com/bre7/Bcrypt-Swift OpenWall's implementation is working, couldn't manage to properly use OpenBSD's one (which lacks 2y support I think)
