### ISSUE TITLE
Default AES mode should not be ECB

### ISSUE THREAD

**Issue by MrMage** [vapor/crypto#59]
Vapor defaults to using AES in ECB mode (see https://github.com/vapor/crypto/blob/346ae2b2ea65a4b6f4985a8e8cb25cf61da549d8/Sources/Crypto/Cipher/Cipher.swift#L13). This has the advantage of not having to choose an initialization vector, but it is problematic in the case where plaintexts are repetitive or can be chosen by the attacker (see https://crypto.stackexchange.com/questions/20941/why-shouldnt-i-use-ecb-encryption for an explanation).

I'd suggest deprecating the currently declared encryption-mode constants in favor of new ones that use CBC, CFB or GCM mode. This makes it necessary to choose an IV, which could automatically be done at random (similar to how we generate a new salt for each Bcrypt hash). (Note that the chosen IV _does_ need to be **stored** (unencrypted) alongside the ciphertext.)

**Comment by tanner0101** [comment]
I agree we should make it easy to use the IV methods, but I would need more convincing to deprecate the existing method. `aes128ecb` seems to be what most other web frameworks offer by default.

**Comment by tanner0101** [comment]
What should the API for generating IVs look like? Maybe just an extension on `Random.DataGenerator`?

**Comment by MrMage** [comment]
Which frameworks are you referring to? For Ruby, it looks like some crypto frameworks _only_ support CBC, and for PHP Stack Overflow is full of people warning _not_ to use ECB.

I would at least suggest deprecating the `aes128` variable in favor of `aes128ecb` to force people to make an informed decision. For encryption to have the desired security properties in a given context, it is crucial to at least have a very basic understanding of what you are doing, and having the `aes128` default makes it too easy to go with "I'll just pick that, it's probably gonna be fine". That's not how crypto should be approached.

In terms of generating an IV, im just using `Crypto random.bytes` (don't recall the exact name right now).

**Comment by MrMage** [comment]
FWIW it appears that Laravel only supports CBC as well: https://laravel.com/docs/5.6/encryption.

**Comment by tanner0101** [comment]
@MrMage thanks for researching that! I agree we should use CBC then.

**Comment by GriffinMB** [comment]
Hi! 

Defaulting to ECB mode should be considered a fairly serious security issue. Details on why can be found here: https://crypto.stackexchange.com/questions/20941/why-shouldnt-i-use-ecb-encryption

Also if you are migrating to CBC mode, note that it should not be used without authentication because it has well-documented issues that can result in secret key disclosure. The above link touches on that a bit, but doesn't go into detail. 

If you are going to use OpenSSL, you should use a proper authenticated cipher like GCM. Though, you would be most secure by wrapping NaCl/libsodium and providing nice bindings to the crypto functions it provides.

**Comment by MrMage** [comment]
Thank you for the feedback! Could you provide more details on the issues with CBC and when exactly they are relevant?

Also, what exactly are the advantages of using libsodium in this case?

**Comment by GriffinMB** [comment]
No problem! The most severe issue with unauthenticated CBC is the potential for [padding oracle attacks](https://en.wikipedia.org/wiki/Padding_oracle_attack), where an attacker can manipulate the ciphertext to disclose message plaintext. You can read more about it (and follow some other links) here: https://www.quora.com/What-are-disadvantages-of-AES-in-CBC-mode

The best practice in modern cryptography is to default to authenticated encryption. Using an encrypt-then-MAC construction, CBC can be perfectly fine, but for a modern web framework it would make more sense to use a real authenticated cipher.

> Also, what exactly are the advantages of using libsodium in this case?

[Libsodium](https://download.libsodium.org/doc/) is great because it is a well-reviewed and well-audited library that provides no-brainer default options that even inexperienced developers can use securely. Libsodium bindings could replace a large portion of this package's API (e.g. RSA, symmetric ciphers) with more secure, more robust options.

**Comment by MrMage** [comment]
@GriffinMB thank you for the elaboration! I have updated https://github.com/vapor/crypto/pull/60 to add deprecations and some explanatory comments; please let me know if you think this is appropriate. Migrating to libsodium would be a longer-term effort in a different pull request.

**Comment by MrMage** [comment]
Update: we currently have no means to extract the GCM tag. So that would probably need to be added before we can use AES-GCM in our current setup. I am not an expert on this, but I presume that we would need to extract the tag and pass it alongside the ciphertext and IV?

We also do not support passing in Additional Authenticated Data at the moment.

**Comment by GriffinMB** [comment]
> I am not an expert on this, but I presume that we would need to extract the tag and pass it alongside the ciphertext and IV?

Yeah! For the implementation, there are often two functions, coupled and decoupled, where you can get the encrypted data with the tag appended, or a tuple with separate encrypted data and tag. 

> We also do not support passing in Additional Authenticated Data at the moment.

I imagine this is fine - a lot of frameworks that expose GCM don't support AAD. [Rails' MessageEncryptor](http://api.rubyonrails.org/v5.2.0/classes/ActiveSupport/MessageEncryptor.html), for example, defaults to GCM and doesn't have any way to pass additional data.

**Comment by tanner0101** [comment]
@MrMage it seems that #60 somehow had the deprecations removed (I remember seeing them in there last time). Do you want to open a PR that contains the deprecations for ECB? I will wait to include that in 3.2.0.

**Comment by MrMage** [comment]
Weird; I must have forgotten to push them or something like that. Filed #66.
