### ISSUE TITLE
OpenSSL 1.1 compatibility

### ISSUE THREAD

**Issue by marc-medley** [vapor/crypto#74]
Update Crypto to be OpenSSL 1.1 compatible.

Ubuntu 18.04 ships with OpenSSL 1.1 as part the standard install.   However, since Crypto is not yet OpenSSL 1.1 compatible, then Vapor on a source level would not be Ubuntu 18.04 compatible. [see [vapor/documentation/issues/359](https://github.com/vapor/documentation/issues/359) comments]

Although an OpenSSL 1.1-compatible Crypto may not happen any time soon due current priorities and/or level of effort required, this issue provides a place to (1) communicate this as a known issue and (2) provide some guidance or milestone as to how far out a Vapor/Crypto with OpenSSL 1.1 might be.

**Comment by 0xTim** [comment]
The other thing blocking this is that Swift doesn't (officially) support 18.04 and it requires NIO to support 1.1 as well (the work of which is almost done)

**Comment by weissi** [comment]
@0xTim yes, NIO's has landed a few days ago in swift-nio-ssl 1.3.1

**Comment by vzsg** [comment]
If only there was a wrapper for EVP, not just the TLS-related functions 😊

**Comment by weissi** [comment]
@vzsg I know... We don't consider any of our OpenSSL bindings public API though. So from NIO's point of view the public API are the TLS channel handlers/options/etc only.
I know that's not a great answer for vapor/crypto but longer term that should rely on the platform's TLS library anyway, right? For example NIO with NIOTransportServices now works fine on iOS and there you wouldn't even use swift-nio-ssl at all because Network.framework is used to provide the TLS functionality. Vapor/crypto won't work on iOS as long as it keeps its OpenSSL dependency (short of vendoring OpenSSL) but the Swift Server Work Group is naturally looking into a cross-platform crypto library that could then be used for vapor/crypto on Linux & Darwin. [IBM's BlueCryptor](https://github.com/IBM-Swift/BlueCryptor) does support OpenSSL 1.0 & CommonCryto already.

**Comment by segabor** [comment]
Sad news. Until this issue is not resolved I give up Vapor on Arch Linux.

**Comment by tanner0101** [comment]
OpenSSL 1.1 support added in #75.

**Comment by segabor** [comment]
Awesome news! This patch just unlocked Vapor on Arch Linux!
Thank you @tanner0101 and team!
