### ISSUE TITLE
Random facilities should utilize Swift's RandomNumberGenerator

### ISSUE THREAD

**Issue by Azoy** [vapor/crypto#77]
I would love to see the Vapor project use Swift's new random features.

**Comment by tanner0101** [comment]
@Azoy +1 to this, I'm very excited to move to Swift's 4.2's new `Random` type. For the current release, I think the most we could do is offer an additional `Random` conformer that uses Swift's `Random` type internally. I don't think that would be of much use, though since it's APIs are already so nice to use. 

Really what we want to do is remove all of Crypto's random protocols and code and rely directly on Swift's random types. The next major release of this package will have a Swift version minimum of 5.0, so that would be an appropriate time to do it.

**Comment by tanner0101** [comment]
CryptoKit 4 utilizes Swift 4.2 random now (#82) see: https://github.com/vapor/crypto/blob/master/Sources/CryptoKit/Random/Random.swift

If there's anything else we should add, let me know. Thanks :)

**Comment by Azoy** [comment]
Fantastic!
